# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'FitnessApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FitnessApp
pod 'Appirater'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Analytics'
pod 'Firebase/Crashlytics'
pod 'Firebase/Storage'
pod 'Firebase/Firestore'

pod 'SDWebImage'

  target 'FitnessAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FitnessAppUITests' do
    # Pods for testing
  end

end
